### ISSUE TITLE
package does not exist

### ISSUE THREAD

**Issue by GGui** [forge/wildfly-swarm-addon#16]
When I execute the command “addon-install-from-git --url https://github.com/forge/wildfly-swarm-addon.git” in forge.
Maven display a compile error. 
"src/main/java/org/jboss/forge/addon/swarm/Swarm.java:[21,40] package org.jboss.forge.addon.javaee.jms does not exist"
I checked the sources and i didn't found this package.

Thanks,
Guillaume

**Comment by gastaldi** [comment]
What Forge version are you using? Can you test in Forge 3.0.0.Beta4?

**Comment by GGui** [comment]
I used forge 2.19.2 with jboss tools in eclipse. I try with the last version 2.20.2.Final and now it work.

Thanks you

**Comment by gastaldi** [comment]
Thanks
