### ISSUE TITLE
@PreMatching annotation issue

### ISSUE THREAD

**Issue by rafabene** [forge/wildfly-swarm-addon#25]
I used the rest-new-cross-origin-resource-sharing-filter command and the generate filter shows the following message in JBDS 9.1:
"The @PreMatching annotation is only allowed on subclasses of javax.ws.rs.container.ContainerRequestFilter" indicating an Error. That forbids JBDS to builds the project.

**Comment by gastaldi** [comment]
Hi @rafabene, this looks like an issue to be discussed in https://issues.jboss.org/browse/FORGE. as it seems to be a core problem. Would you mind creating the issue there? 

PS: I haven't seen any problem when running the project, maybe it's a JBDS thing? 

Thanks!

**Comment by rafabene** [comment]
Sure. Reported as https://issues.jboss.org/browse/FORGE-2639

**Comment by gastaldi** [comment]
Thank you. Will push a fix asap
