### ISSUE TITLE
Call "fraction-detect" when a "non detectable" fraction is added.

### ISSUE THREAD

**Issue by sebastienblanc** [forge/wildfly-swarm-addon#34]
From my own experience this morning :) : 
I was not aware of the "detectFraction" configuration that run only if no fractions are in the POM. So, my simple REST app was working fine. Then I added the "keycloak" fraction but (and it took me some time  before I realize) then when running my app again, the app was not working becausethe jaxrs fraction was not added anymore (since the detection was not running). 
I know you can set "detectionFraction" to "force" but when using the Forge addon and adding manually a fraction, I think we should call "detect fraction" (and save to the POM). 
(Not sure my explanation is clear :) )

**Comment by gastaldi** [comment]
Would it work if we add a `detectionFraction` option in `wildfly-swarm-setup` that will configure that option in the maven plugin?

**Comment by gastaldi** [comment]
I've gotta say that I've run into the same issue too.

**Comment by sebastienblanc** [comment]
That is an option but it still doesn't make it really clear for someone that does not know how `detectFraction` works. Not sure what the best flow is , UX wize ...

**Comment by gastaldi** [comment]
The `wildfly-swarm-detect-fractions` command should detect and add the missing fractions when `--depend --build` is specified. Closing issue for now
